name: Renchant
main: me.varmetek.renchant.Renchant
version: 1.0.0
description: A plugin that allows for the re-enchantment of items
authors: [Varmetek]
permissions:
  renchant.use:
    default: op
    description: Allows users to use the plugin's functions.